# Generated by Django 5.0.1 on 2024-08-19 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FountainChurchMainHeadImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fountain_church_img_title', models.CharField(blank=True, max_length=255, null=True)),
                ('fountain_church_img_description', models.TextField()),
                ('fountain_church_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('fountain_church_img_img', models.ImageField(upload_to='img/')),
                ('fountain_church_img_date', models.DateTimeField(auto_now_add=True)),
                ('fountain_church_img_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fountain_church_img_date'],
            },
        ),
    ]
