# Generated by Django 5.0.1 on 2024-08-19 22:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0004_fountainchurchtestimony'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FountainChurchTestimony',
            new_name='FountainChurchMinisterHome',
        ),
        migrations.AlterModelOptions(
            name='fountainchurchministerhome',
            options={'ordering': ['-fountain_church_minister_home_date']},
        ),
        migrations.RenameField(
            model_name='fountainchurchministerhome',
            old_name='fountain_church_testimony_author',
            new_name='fountain_church_minister_home_author',
        ),
        migrations.RenameField(
            model_name='fountainchurchministerhome',
            old_name='fountain_church_testimony_date',
            new_name='fountain_church_minister_home_date',
        ),
        migrations.RenameField(
            model_name='fountainchurchministerhome',
            old_name='fountain_church_testimony_description',
            new_name='fountain_church_minister_home_description',
        ),
        migrations.RenameField(
            model_name='fountainchurchministerhome',
            old_name='fountain_church_testimony_img',
            new_name='fountain_church_minister_home_img',
        ),
        migrations.RenameField(
            model_name='fountainchurchministerhome',
            old_name='fountain_church_testimony_title',
            new_name='fountain_church_minister_home_title',
        ),
    ]
