# Generated by Django 5.0.1 on 2024-08-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0008_churchevent_events_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchevent',
            name='Events_date_event',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
