# Generated by Django 5.0.1 on 2024-08-21 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0009_churchevent_events_date_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=255, null=True)),
                ('blog_description', models.TextField()),
                ('blog_slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('blog_img', models.ImageField(upload_to='blog_img/')),
                ('blog_date', models.DateTimeField(auto_now_add=True)),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-blog_date'],
            },
        ),
    ]
