# Generated by Django 5.0.1 on 2024-08-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0011_churchsermons'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchsermons',
            name='Sermons_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
