# Generated by Django 5.0.1 on 2024-08-28 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0013_churchgalary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchgalary',
            name='galary_img',
            field=models.ImageField(upload_to='galary_img/'),
        ),
        migrations.CreateModel(
            name='Pastors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pastor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pastor_position', models.CharField(blank=True, max_length=100, null=True)),
                ('pastor_img', models.ImageField(upload_to='pass_img/')),
                ('pastor_date', models.DateTimeField(auto_now_add=True)),
                ('pastor_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pastor_date'],
            },
        ),
    ]
