# Generated by Django 5.0.1 on 2024-08-28 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0015_mainpicture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mainpicture',
        ),
    ]
