# Generated by Django 5.1.5 on 2025-02-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0016_delete_mainpicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactvideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_video', models.FileField(upload_to='contact_videos/')),
            ],
        ),
    ]
