# Generated by Django 5.1.5 on 2025-02-03 12:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0017_contactvideo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ChurchSermons',
            new_name='ChurchVideoSermons',
        ),
    ]
