# Generated by Django 5.1.5 on 2025-02-03 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0018_rename_churchsermons_churchvideosermons'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchAudioSermons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_sermons_title', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_Sermons_time', models.CharField(blank=True, max_length=255, null=True)),
                ('audio_sermons_description', models.TextField()),
                ('audio_sermons_preach_by', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_sermons', models.FileField(upload_to='audio/')),
                ('audio_sermons_publish_date', models.DateTimeField(auto_now_add=True)),
                ('audio_sermons_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-audio_sermons_publish_date'],
            },
        ),
    ]
