# Generated by Django 5.1.5 on 2025-02-03 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0019_churchaudiosermons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchaudiosermons',
            name='audio_sermons_title',
        ),
    ]
