# Generated by Django 5.1.5 on 2025-02-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0021_remove_churchaudiosermons_audio_sermons_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchaudiosermons',
            name='audio_sermons_title',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
