# Generated by Django 5.1.5 on 2025-02-10 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0022_alter_churchaudiosermons_audio_sermons_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='churchaudiosermons',
            name='sermon_image',
            field=models.ImageField(blank=True, null=True, upload_to='sermon_images/'),
        ),
    ]
