# Generated by Django 5.1.5 on 2025-02-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0024_alter_churchaudiosermons_sermon_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='churchaudiosermons',
            name='sermon_image',
            field=models.ImageField(blank=True, null=True, upload_to='sermon_images/'),
        ),
    ]
