# Generated by Django 5.1.5 on 2025-02-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0025_alter_churchaudiosermons_sermon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='churchaudiosermons',
            name='sermon_image',
        ),
    ]
