# Generated by Django 5.1.5 on 2025-02-17 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fountain', '0026_remove_churchaudiosermons_sermon_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fountainchurchmainheadimage',
            name='fountain_church_img_img',
        ),
        migrations.AddField(
            model_name='fountainchurchmainheadimage',
            name='fountain_church_video',
            field=models.FileField(default=1, upload_to='head_videos/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ChurchBlog',
        ),
    ]
